openapi: 3.0.0
info:
  title: ""
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: "Say Hello"
      # the description is intentionally missing to trigger the rule
      responses:
        '200':
          description: OK

